### ISSUE TITLE
make final screen more substantial

### ISSUE THREAD

**Issue by tkoterwas** [ox-it/sensing-evolution#26]
And the final screen is a bit flat as a reward for having completed everything. Would it be possible have a fuller thing, which reprises the eight images in the trail, maybe in a 2x4 grid (2 rows, 4 columns) of square crops (I can make this if need be – let me know), along with copy as in the Google doc mentioned above.

**Comment by ahaith** [comment]
Image grid and Scott's text have been added to the screen, but are as-yet unstyled.

**Comment by ahaith** [comment]
Worth @tkoterwas reviewing, but it's in reasonable shape now.
